Repository ohdnf/marbling, pull requests merged in 2022-08, with the labels that each got.

#1 README.md 수정
  README.md
Labels: enhancement

#3 홍주표: 멀쩡한 사각형 추가 (#2)
  멀쩡한사각형/jupyo.js
Labels: 해결🌈

#6 이다은: 멀쩡한 사각형 (#2)
  멀쩡한사각형/daeun.js
Labels: 해결🌈

#5 조상래래: 멀쩡한 사각형 풀이
  멀쩡한사각형/sangrae.js
Labels: 해결🌈

#10 문서: gitignore 추가
  .gitignore
  README.md
  행렬테두리회전하기/jupyo.js
Labels: 문서📝

#11 홍주표: 행렬 테두리 회전하기 (#8)
  행렬테두리회전하기/jupyo.js
Labels: 해결🌈

#12 조상래: 행렬테두리회전하기 풀이
  행렬테두리회전하기/sangrae.js
Labels: 해결🌈, 여기요🙋🏻

#14 조상래: 메뉴 리뉴얼 풀이
  메뉴리뉴얼/sangrae.js
Labels: 해결🌈

#15 README.md 수정
  README.md
Labels: 문서📝
